extends Node

@warning_ignore("unused_signal")
signal state_changed(snapshot: StateSnapshotPayload)
@warning_ignore("unused_signal")
signal feature_added(card: FeatureCard)
@warning_ignore("unused_signal")
signal interaction_triggered(event_data: InteractionEventPayload)
@warning_ignore("unused_signal")
signal threshold_event(event_data: ThresholdEventPayload)
@warning_ignore("unused_signal")
signal dilemma_offered(event_data: DilemmaOfferPayload)
@warning_ignore("unused_signal")
signal draft_offer(event_data: DraftOfferPayload)
@warning_ignore("unused_signal")
signal publisher_meeting_offered(event_data: PublisherMeetingOfferPayload)
@warning_ignore("unused_signal")
signal run_identity_changed(event_data: RunIdentityPayload)
@warning_ignore("unused_signal")
signal day_spent(event_data: DaySpentPayload)
@warning_ignore("unused_signal")
signal runway_depleted(event_data: RunwayDepletedPayload)
@warning_ignore("unused_signal")
signal reviews_generated(results: ReviewsGeneratedPayload)
@warning_ignore("unused_signal")
signal stage_changed(theme: StageTheme)
@warning_ignore("unused_signal")
signal archetype_chosen(archetype: String)
